# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Comments',
            new_name='comments',
        ),
    ]
