# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0004_auto_20180514_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
