# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0009_auto_20180516_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
